INSERT INTO regioni(nome) VALUES
  ('Sardegna'), 
  ('Lombardia'), 
  ('Liguria');

INSERT INTO citta(nome, id_regione) VALUES
  ('Cagliari', 1), 
  ('Oristano', 1), 
  ('Sassari', 1), 
  ('Tempio', 1), 
  ('Olbia', 1), 
  ('Porto Torres', 1), 
  ('Nuoro', 1), 
  ('Alghero', 1), 
  ('Bosa', 1), 
  ('Sorso', 1), 
  ('Oschiri', 1), 
  ('Bessude', 1), 
  ('Milano', 2), 
  ('Varese', 2), 
  ('Pavia', 2), 
  ('Brescia', 2), 
  ('Monza', 2), 
  ('Como', 2), 
  ('Viadana', 2), 
  ('Teglio', 2), 
  ('Genova', 3), 
  ('Savona', 3), 
  ('Rapallo', 3), 
  ('Sanremo', 3), 
  ('Alassio', 3), 
  ('Chiavari', 3), 
  ('Legnano', 3), 
  ('Noli', 3), 
  ('La Spezia', 3), 
  ('Imperia', 3);

INSERT INTO utenti(username, passw, id_citta) VALUES
  ('Alberto', 'jinii', 3), 
  ('Eliana', 'jinii', 3), 
  ('Luca', 'jinii', 3), 
  ('Roberto', 'jinii', null), 
  ('Filippo', 'jinii', null), 
  ('Giampiero', 'jinii', 8), 
  ('Mario', 'jinii', null), 
  ('Roberto', 'jinii', 15), 
  ('Daniele', 'jinii', 6), 
  ('Alessandro', 'jinii', 10), 
  ('Mirko', 'jinii', 6), 
  ('Salvatore', 'jinii', 11), 
  ('Riccardo', 'jinii', 23), 
  ('Lorenzo', 'jinii', 8),
  ('Claudia', 'jinii', 13), 
  ('Gianfranco', 'jinii', 3), 
  ('Fabio', 'jinii', 8), 
  ('Simona', 'jinii', 7), 
  ('Antonio', 'jinii', 6), 
  ('Federico', 'jinii', 21), 
  ('Antonello', 'jinii', null), 
  ('Marco', 'jinii',3), 
  ('Sergio', 'jinii', 3), 
  ('Lorenzo', 'jinii', 7);